
// 请求错误
export const REQUEST_FAILED = 'REQUEST_FAILED';
// 单元学习请求成功
export const STUDYUNITDETAILSSUCCESS = 'STUDYUNITDETAILSSUCCESS';
// 单元学习详情请求成功
export const STUDYUNITSUCCESS = 'STUDYUNITSUCCESS';
